apiVersion: apps/v1
kind: Deployment
metadata:
  name: okao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okao
  template:
    metadata:
      labels:
        app: okao
    spec:
      containers:
      - image: okteto.dev/okao:latest
        name: okao
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "972186dd-e3ad-4ad9-9535-b80b088a8317"
        - name: Vless_Path
          value: "/gfhtfytsgf"
        - name: Vmess_UUID
          value: "972186dd-e3ad-4ad9-9535-b80b088a8317"
        - name: Vmess_Path
          value: "/sgdggduhfe"
        - name: Share_Path
          value: "/dgefsbdd"
